---
server:
  ipaddr: localhost
  port: 5790

client:
  ipaddr: localhost
  port: 5789

target_server:
  localhost:
    ipaddr: 192.168.0.187
    port: 32768
    username: admin
    password:
    keyfile: ~/.ssh/id_rsa

bot:
  token: 928771573:AAFjz31if1zs543Ml535gGSAtk38HqdJIWE

logging:
  level: debug
  mode: development # production or development
  filelogging:
    use: True
    logfilepath: ./
    logfilename: bot.log

...