# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import network_pb2 as network__pb2


class NetworkStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CmdRequest = channel.unary_unary(
        '/network.Network/CmdRequest',
        request_serializer=network__pb2.Request.SerializeToString,
        response_deserializer=network__pb2.Response.FromString,
        )


class NetworkServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CmdRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NetworkServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CmdRequest': grpc.unary_unary_rpc_method_handler(
          servicer.CmdRequest,
          request_deserializer=network__pb2.Request.FromString,
          response_serializer=network__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'network.Network', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
